//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: fructus
// ----------------------------------------------------------------------------
pub mod fructus {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for fructus
    pub fn program_id() -> Pubkey {
        pubkey!("8ZLiJ12eBiam4UP2HRp3M75CQAcc8GuUBz44zeHt6mjH")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub publisher: Pubkey,

        pub stale_after_slots: u64,

        pub initial_apy: u64,
    }

    impl InitializeInstructionData {
        pub fn new(publisher: Pubkey, stale_after_slots: u64, initial_apy: u64) -> Self {
            Self {
                publisher,

                stale_after_slots,

                initial_apy,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetPublisher
    // ....................................................................

    /// Main instruction struct for SetPublisher
    pub struct SetPublisherInstruction {
        pub accounts: SetPublisherInstructionAccountMetas,
        pub data: SetPublisherInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetPublisher instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetPublisherInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for SetPublisher instruction
    #[derive(Debug, Clone)]
    pub struct SetPublisherInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl SetPublisherInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for SetPublisher
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetPublisherInstructionData {
        pub new_publisher: Pubkey,
    }

    impl SetPublisherInstructionData {
        pub fn new(new_publisher: Pubkey) -> Self {
            Self { new_publisher }
        }
    }

    /// Implementation for SetPublisherInstruction
    impl SetPublisherInstruction {
        fn discriminator() -> [u8; 8] {
            [110u8, 54u8, 4u8, 216u8, 151u8, 85u8, 46u8, 91u8]
        }

        pub fn data(data: SetPublisherInstructionData) -> Self {
            Self {
                accounts: SetPublisherInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetPublisherInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetStaleWindow
    // ....................................................................

    /// Main instruction struct for SetStaleWindow
    pub struct SetStaleWindowInstruction {
        pub accounts: SetStaleWindowInstructionAccountMetas,
        pub data: SetStaleWindowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetStaleWindow instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetStaleWindowInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for SetStaleWindow instruction
    #[derive(Debug, Clone)]
    pub struct SetStaleWindowInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl SetStaleWindowInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for SetStaleWindow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetStaleWindowInstructionData {
        pub new_stale_after_slots: u64,
    }

    impl SetStaleWindowInstructionData {
        pub fn new(new_stale_after_slots: u64) -> Self {
            Self {
                new_stale_after_slots,
            }
        }
    }

    /// Implementation for SetStaleWindowInstruction
    impl SetStaleWindowInstruction {
        fn discriminator() -> [u8; 8] {
            [189u8, 158u8, 76u8, 38u8, 2u8, 227u8, 121u8, 34u8]
        }

        pub fn data(data: SetStaleWindowInstructionData) -> Self {
            Self {
                accounts: SetStaleWindowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetStaleWindowInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateApy
    // ....................................................................

    /// Main instruction struct for UpdateApy
    pub struct UpdateApyInstruction {
        pub accounts: UpdateApyInstructionAccountMetas,
        pub data: UpdateApyInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateApy instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateApyInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub instruction_sysvar: AccountMeta,
    }

    /// Account pubkeys for UpdateApy instruction
    #[derive(Debug, Clone)]
    pub struct UpdateApyInstructionAccounts {
        pub oracle: Pubkey,

        pub instruction_sysvar: Pubkey,
    }

    impl UpdateApyInstructionAccounts {
        pub fn new(oracle: Pubkey, instruction_sysvar: Pubkey) -> Self {
            Self {
                oracle,

                instruction_sysvar,
            }
        }
    }

    /// Instruction data for UpdateApy
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateApyInstructionData {
        pub apy: u64,

        pub version: u64,
    }

    impl UpdateApyInstructionData {
        pub fn new(apy: u64, version: u64) -> Self {
            Self { apy, version }
        }
    }

    /// Implementation for UpdateApyInstruction
    impl UpdateApyInstruction {
        fn discriminator() -> [u8; 8] {
            [94u8, 110u8, 147u8, 45u8, 73u8, 167u8, 222u8, 77u8]
        }

        pub fn data(data: UpdateApyInstructionData) -> Self {
            Self {
                accounts: UpdateApyInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateApyInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.instruction_sysvar =
                AccountMeta::new_readonly(accounts.instruction_sysvar, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.instruction_sysvar.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: YieldOracle
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct YieldOracle {
    pub apy: u64,

    pub version: u64,

    pub last_update_slot: u64,

    pub publisher: Pubkey,

    pub authority: Pubkey,

    pub stale_after_slots: u64,

    pub bump: u8,
}

impl YieldOracle {
    pub fn new(
        apy: u64,

        version: u64,

        last_update_slot: u64,

        publisher: Pubkey,

        authority: Pubkey,

        stale_after_slots: u64,

        bump: u8,
    ) -> Self {
        Self {
            apy,

            version,

            last_update_slot,

            publisher,

            authority,

            stale_after_slots,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
