//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: fructus
// ----------------------------------------------------------------------------
pub mod fructus {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for fructus
    pub fn program_id() -> Pubkey {
        pubkey!("8ZLiJ12eBiam4UP2HRp3M75CQAcc8GuUBz44zeHt6mjH")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CancelOrder
    // ....................................................................

    /// Main instruction struct for CancelOrder
    pub struct CancelOrderInstruction {
        pub accounts: CancelOrderInstructionAccountMetas,
        pub data: CancelOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelOrderInstructionAccountMetas {
        pub order_book: AccountMeta,

        pub market: AccountMeta,

        pub owner: AccountMeta,
    }

    /// Account pubkeys for CancelOrder instruction
    #[derive(Debug, Clone)]
    pub struct CancelOrderInstructionAccounts {
        pub order_book: Pubkey,

        pub market: Pubkey,

        pub owner: Pubkey,
    }

    impl CancelOrderInstructionAccounts {
        pub fn new(order_book: Pubkey, market: Pubkey, owner: Pubkey) -> Self {
            Self {
                order_book,

                market,

                owner,
            }
        }
    }

    /// Instruction data for CancelOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelOrderInstructionData {
        pub seq: u64,
    }

    impl CancelOrderInstructionData {
        pub fn new(seq: u64) -> Self {
            Self { seq }
        }
    }

    /// Implementation for CancelOrderInstruction
    impl CancelOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [95u8, 129u8, 237u8, 240u8, 8u8, 49u8, 223u8, 132u8]
        }

        pub fn data(data: CancelOrderInstructionData) -> Self {
            Self {
                accounts: CancelOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelOrderInstructionAccounts) -> Self {
            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.owner.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClosePosition
    // ....................................................................

    /// Main instruction struct for ClosePosition
    pub struct ClosePositionInstruction {
        pub accounts: ClosePositionInstructionAccountMetas,
        pub data: ClosePositionInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClosePosition instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClosePositionInstructionAccountMetas {
        pub owner: AccountMeta,

        pub market: AccountMeta,

        pub order_book: AccountMeta,

        pub index_source: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,
    }

    /// Account pubkeys for ClosePosition instruction
    #[derive(Debug, Clone)]
    pub struct ClosePositionInstructionAccounts {
        pub owner: Pubkey,

        pub market: Pubkey,

        pub order_book: Pubkey,

        pub index_source: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,
    }

    impl ClosePositionInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            market: Pubkey,

            order_book: Pubkey,

            index_source: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,
        ) -> Self {
            Self {
                owner,

                market,

                order_book,

                index_source,

                position,

                user_collateral,
            }
        }
    }

    /// Instruction data for ClosePosition
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClosePositionInstructionData {
        pub side: u8,

        pub size: u64,
    }

    impl ClosePositionInstructionData {
        pub fn new(side: u8, size: u64) -> Self {
            Self { side, size }
        }
    }

    /// Implementation for ClosePositionInstruction
    impl ClosePositionInstruction {
        fn discriminator() -> [u8; 8] {
            [123u8, 134u8, 81u8, 0u8, 49u8, 68u8, 98u8, 98u8]
        }

        pub fn data(data: ClosePositionInstructionData) -> Self {
            Self {
                accounts: ClosePositionInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClosePositionInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Crank
    // ....................................................................

    /// Main instruction struct for Crank
    pub struct CrankInstruction {
        pub accounts: CrankInstructionAccountMetas,
        pub data: CrankInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Crank instruction
    #[derive(Debug, Clone, Default)]
    pub struct CrankInstructionAccountMetas {
        pub order_book: AccountMeta,

        pub market: AccountMeta,

        pub index_source: AccountMeta,

        pub cranker: AccountMeta,
    }

    /// Account pubkeys for Crank instruction
    #[derive(Debug, Clone)]
    pub struct CrankInstructionAccounts {
        pub order_book: Pubkey,

        pub market: Pubkey,

        pub index_source: Pubkey,

        pub cranker: Pubkey,
    }

    impl CrankInstructionAccounts {
        pub fn new(
            order_book: Pubkey,

            market: Pubkey,

            index_source: Pubkey,

            cranker: Pubkey,
        ) -> Self {
            Self {
                order_book,

                market,

                index_source,

                cranker,
            }
        }
    }

    /// Instruction data for Crank
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CrankInstructionData {}

    impl CrankInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CrankInstruction
    impl CrankInstruction {
        fn discriminator() -> [u8; 8] {
            [0u8, 232u8, 3u8, 195u8, 124u8, 117u8, 105u8, 53u8]
        }

        pub fn data(data: CrankInstructionData) -> Self {
            Self {
                accounts: CrankInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CrankInstructionAccounts) -> Self {
            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.cranker = AccountMeta::new_readonly(accounts.cranker, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.cranker.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositCollateral
    // ....................................................................

    /// Main instruction struct for DepositCollateral
    pub struct DepositCollateralInstruction {
        pub accounts: DepositCollateralInstructionAccountMetas,
        pub data: DepositCollateralInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositCollateral instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositCollateralInstructionAccountMetas {
        pub user: AccountMeta,

        pub market: AccountMeta,

        pub user_collateral: AccountMeta,

        pub vault: AccountMeta,

        pub user_ata: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for DepositCollateral instruction
    #[derive(Debug, Clone)]
    pub struct DepositCollateralInstructionAccounts {
        pub user: Pubkey,

        pub market: Pubkey,

        pub user_collateral: Pubkey,

        pub vault: Pubkey,

        pub user_ata: Pubkey,

        pub collateral_mint: Pubkey,
    }

    impl DepositCollateralInstructionAccounts {
        pub fn new(
            user: Pubkey,

            market: Pubkey,

            user_collateral: Pubkey,

            vault: Pubkey,

            user_ata: Pubkey,

            collateral_mint: Pubkey,
        ) -> Self {
            Self {
                user,

                market,

                user_collateral,

                vault,

                user_ata,

                collateral_mint,
            }
        }
    }

    /// Instruction data for DepositCollateral
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositCollateralInstructionData {
        pub amount: u64,
    }

    impl DepositCollateralInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for DepositCollateralInstruction
    impl DepositCollateralInstruction {
        fn discriminator() -> [u8; 8] {
            [156u8, 131u8, 142u8, 116u8, 146u8, 247u8, 162u8, 120u8]
        }

        pub fn data(data: DepositCollateralInstructionData) -> Self {
            Self {
                accounts: DepositCollateralInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositCollateralInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.user_ata = AccountMeta::new(accounts.user_ata, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.user_ata.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub publisher: Pubkey,

        pub stale_after_slots: u64,

        pub initial_apy: u64,
    }

    impl InitializeInstructionData {
        pub fn new(publisher: Pubkey, stale_after_slots: u64, initial_apy: u64) -> Self {
            Self {
                publisher,

                stale_after_slots,

                initial_apy,
            }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeCollateralVault
    // ....................................................................

    /// Main instruction struct for InitializeCollateralVault
    pub struct InitializeCollateralVaultInstruction {
        pub accounts: InitializeCollateralVaultInstructionAccountMetas,
        pub data: InitializeCollateralVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeCollateralVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeCollateralVaultInstructionAccountMetas {
        pub market: AccountMeta,

        pub authority: AccountMeta,

        pub payer: AccountMeta,

        pub vault: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for InitializeCollateralVault instruction
    #[derive(Debug, Clone)]
    pub struct InitializeCollateralVaultInstructionAccounts {
        pub market: Pubkey,

        pub authority: Pubkey,

        pub payer: Pubkey,

        pub vault: Pubkey,

        pub collateral_mint: Pubkey,
    }

    impl InitializeCollateralVaultInstructionAccounts {
        pub fn new(
            market: Pubkey,

            authority: Pubkey,

            payer: Pubkey,

            vault: Pubkey,

            collateral_mint: Pubkey,
        ) -> Self {
            Self {
                market,

                authority,

                payer,

                vault,

                collateral_mint,
            }
        }
    }

    /// Instruction data for InitializeCollateralVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeCollateralVaultInstructionData {}

    impl InitializeCollateralVaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeCollateralVaultInstruction
    impl InitializeCollateralVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [50u8, 63u8, 54u8, 33u8, 53u8, 166u8, 24u8, 61u8]
        }

        pub fn data(data: InitializeCollateralVaultInstructionData) -> Self {
            Self {
                accounts: InitializeCollateralVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeCollateralVaultInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeMarket
    // ....................................................................

    /// Main instruction struct for InitializeMarket
    pub struct InitializeMarketInstruction {
        pub accounts: InitializeMarketInstructionAccountMetas,
        pub data: InitializeMarketInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeMarket instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeMarketInstructionAccountMetas {
        pub market: AccountMeta,

        pub index_source: AccountMeta,

        pub authority: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeMarket instruction
    #[derive(Debug, Clone)]
    pub struct InitializeMarketInstructionAccounts {
        pub market: Pubkey,

        pub index_source: Pubkey,

        pub authority: Pubkey,

        pub payer: Pubkey,
    }

    impl InitializeMarketInstructionAccounts {
        pub fn new(market: Pubkey, index_source: Pubkey, authority: Pubkey, payer: Pubkey) -> Self {
            Self {
                market,

                index_source,

                authority,

                payer,
            }
        }
    }

    /// Instruction data for InitializeMarket
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeMarketInstructionData {
        pub collateral_mint: Pubkey,

        pub funding_k: u64,

        pub max_funding: u64,

        pub funding_epoch_slots: u64,

        pub initial_margin_bps: u16,

        pub maintenance_margin_bps: u16,
    }

    impl InitializeMarketInstructionData {
        pub fn new(
            collateral_mint: Pubkey,

            funding_k: u64,

            max_funding: u64,

            funding_epoch_slots: u64,

            initial_margin_bps: u16,

            maintenance_margin_bps: u16,
        ) -> Self {
            Self {
                collateral_mint,

                funding_k,

                max_funding,

                funding_epoch_slots,

                initial_margin_bps,

                maintenance_margin_bps,
            }
        }
    }

    /// Implementation for InitializeMarketInstruction
    impl InitializeMarketInstruction {
        fn discriminator() -> [u8; 8] {
            [35u8, 35u8, 189u8, 193u8, 155u8, 48u8, 170u8, 203u8]
        }

        pub fn data(data: InitializeMarketInstructionData) -> Self {
            Self {
                accounts: InitializeMarketInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeMarketInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeOrderBook
    // ....................................................................

    /// Main instruction struct for InitializeOrderBook
    pub struct InitializeOrderBookInstruction {
        pub accounts: InitializeOrderBookInstructionAccountMetas,
        pub data: InitializeOrderBookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeOrderBook instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeOrderBookInstructionAccountMetas {
        pub order_book: AccountMeta,

        pub market: AccountMeta,

        pub authority: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeOrderBook instruction
    #[derive(Debug, Clone)]
    pub struct InitializeOrderBookInstructionAccounts {
        pub order_book: Pubkey,

        pub market: Pubkey,

        pub authority: Pubkey,

        pub payer: Pubkey,
    }

    impl InitializeOrderBookInstructionAccounts {
        pub fn new(order_book: Pubkey, market: Pubkey, authority: Pubkey, payer: Pubkey) -> Self {
            Self {
                order_book,

                market,

                authority,

                payer,
            }
        }
    }

    /// Instruction data for InitializeOrderBook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeOrderBookInstructionData {}

    impl InitializeOrderBookInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeOrderBookInstruction
    impl InitializeOrderBookInstruction {
        fn discriminator() -> [u8; 8] {
            [93u8, 233u8, 9u8, 128u8, 33u8, 199u8, 152u8, 88u8]
        }

        pub fn data(data: InitializeOrderBookInstructionData) -> Self {
            Self {
                accounts: InitializeOrderBookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeOrderBookInstructionAccounts) -> Self {
            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Liquidate
    // ....................................................................

    /// Main instruction struct for Liquidate
    pub struct LiquidateInstruction {
        pub accounts: LiquidateInstructionAccountMetas,
        pub data: LiquidateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Liquidate instruction
    #[derive(Debug, Clone, Default)]
    pub struct LiquidateInstructionAccountMetas {
        pub market: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,

        pub order_book: AccountMeta,

        pub index_source: AccountMeta,

        pub liquidator: AccountMeta,

        pub liquidator_collateral: AccountMeta,
    }

    /// Account pubkeys for Liquidate instruction
    #[derive(Debug, Clone)]
    pub struct LiquidateInstructionAccounts {
        pub market: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,

        pub order_book: Pubkey,

        pub index_source: Pubkey,

        pub liquidator: Pubkey,

        pub liquidator_collateral: Pubkey,
    }

    impl LiquidateInstructionAccounts {
        pub fn new(
            market: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,

            order_book: Pubkey,

            index_source: Pubkey,

            liquidator: Pubkey,

            liquidator_collateral: Pubkey,
        ) -> Self {
            Self {
                market,

                position,

                user_collateral,

                order_book,

                index_source,

                liquidator,

                liquidator_collateral,
            }
        }
    }

    /// Instruction data for Liquidate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct LiquidateInstructionData {
        pub amount: u64,
    }

    impl LiquidateInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for LiquidateInstruction
    impl LiquidateInstruction {
        fn discriminator() -> [u8; 8] {
            [223u8, 179u8, 226u8, 125u8, 48u8, 46u8, 39u8, 74u8]
        }

        pub fn data(data: LiquidateInstructionData) -> Self {
            Self {
                accounts: LiquidateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: LiquidateInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.order_book = AccountMeta::new_readonly(accounts.order_book, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.liquidator = AccountMeta::new_readonly(accounts.liquidator, true);

            self.accounts.liquidator_collateral =
                AccountMeta::new(accounts.liquidator_collateral, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.liquidator.clone());

            metas.push(self.accounts.liquidator_collateral.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: OpenPosition
    // ....................................................................

    /// Main instruction struct for OpenPosition
    pub struct OpenPositionInstruction {
        pub accounts: OpenPositionInstructionAccountMetas,
        pub data: OpenPositionInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for OpenPosition instruction
    #[derive(Debug, Clone, Default)]
    pub struct OpenPositionInstructionAccountMetas {
        pub owner: AccountMeta,

        pub market: AccountMeta,

        pub order_book: AccountMeta,

        pub index_source: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for OpenPosition instruction
    #[derive(Debug, Clone)]
    pub struct OpenPositionInstructionAccounts {
        pub owner: Pubkey,

        pub market: Pubkey,

        pub order_book: Pubkey,

        pub index_source: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,
    }

    impl OpenPositionInstructionAccounts {
        pub fn new(
            owner: Pubkey,

            market: Pubkey,

            order_book: Pubkey,

            index_source: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,
        ) -> Self {
            Self {
                owner,

                market,

                order_book,

                index_source,

                position,

                user_collateral,
            }
        }
    }

    /// Instruction data for OpenPosition
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct OpenPositionInstructionData {
        pub side: u8,

        pub size: u64,

        pub price: u64,
    }

    impl OpenPositionInstructionData {
        pub fn new(side: u8, size: u64, price: u64) -> Self {
            Self { side, size, price }
        }
    }

    /// Implementation for OpenPositionInstruction
    impl OpenPositionInstruction {
        fn discriminator() -> [u8; 8] {
            [135u8, 128u8, 47u8, 77u8, 15u8, 152u8, 240u8, 49u8]
        }

        pub fn data(data: OpenPositionInstructionData) -> Self {
            Self {
                accounts: OpenPositionInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: OpenPositionInstructionAccounts) -> Self {
            self.accounts.owner = AccountMeta::new(accounts.owner, true);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PlaceLimitOrder
    // ....................................................................

    /// Main instruction struct for PlaceLimitOrder
    pub struct PlaceLimitOrderInstruction {
        pub accounts: PlaceLimitOrderInstructionAccountMetas,
        pub data: PlaceLimitOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PlaceLimitOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct PlaceLimitOrderInstructionAccountMetas {
        pub order_book: AccountMeta,

        pub market: AccountMeta,

        pub index_source: AccountMeta,

        pub owner: AccountMeta,
    }

    /// Account pubkeys for PlaceLimitOrder instruction
    #[derive(Debug, Clone)]
    pub struct PlaceLimitOrderInstructionAccounts {
        pub order_book: Pubkey,

        pub market: Pubkey,

        pub index_source: Pubkey,

        pub owner: Pubkey,
    }

    impl PlaceLimitOrderInstructionAccounts {
        pub fn new(
            order_book: Pubkey,

            market: Pubkey,

            index_source: Pubkey,

            owner: Pubkey,
        ) -> Self {
            Self {
                order_book,

                market,

                index_source,

                owner,
            }
        }
    }

    /// Instruction data for PlaceLimitOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PlaceLimitOrderInstructionData {
        pub side: u8,

        pub price: u64,

        pub size: u64,
    }

    impl PlaceLimitOrderInstructionData {
        pub fn new(side: u8, price: u64, size: u64) -> Self {
            Self { side, price, size }
        }
    }

    /// Implementation for PlaceLimitOrderInstruction
    impl PlaceLimitOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [108u8, 176u8, 33u8, 186u8, 146u8, 229u8, 1u8, 197u8]
        }

        pub fn data(data: PlaceLimitOrderInstructionData) -> Self {
            Self {
                accounts: PlaceLimitOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PlaceLimitOrderInstructionAccounts) -> Self {
            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.owner.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PlaceMarketOrder
    // ....................................................................

    /// Main instruction struct for PlaceMarketOrder
    pub struct PlaceMarketOrderInstruction {
        pub accounts: PlaceMarketOrderInstructionAccountMetas,
        pub data: PlaceMarketOrderInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PlaceMarketOrder instruction
    #[derive(Debug, Clone, Default)]
    pub struct PlaceMarketOrderInstructionAccountMetas {
        pub order_book: AccountMeta,

        pub market: AccountMeta,

        pub index_source: AccountMeta,

        pub owner: AccountMeta,
    }

    /// Account pubkeys for PlaceMarketOrder instruction
    #[derive(Debug, Clone)]
    pub struct PlaceMarketOrderInstructionAccounts {
        pub order_book: Pubkey,

        pub market: Pubkey,

        pub index_source: Pubkey,

        pub owner: Pubkey,
    }

    impl PlaceMarketOrderInstructionAccounts {
        pub fn new(
            order_book: Pubkey,

            market: Pubkey,

            index_source: Pubkey,

            owner: Pubkey,
        ) -> Self {
            Self {
                order_book,

                market,

                index_source,

                owner,
            }
        }
    }

    /// Instruction data for PlaceMarketOrder
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PlaceMarketOrderInstructionData {
        pub side: u8,

        pub size: u64,
    }

    impl PlaceMarketOrderInstructionData {
        pub fn new(side: u8, size: u64) -> Self {
            Self { side, size }
        }
    }

    /// Implementation for PlaceMarketOrderInstruction
    impl PlaceMarketOrderInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 118u8, 192u8, 252u8, 192u8, 99u8, 39u8, 145u8]
        }

        pub fn data(data: PlaceMarketOrderInstructionData) -> Self {
            Self {
                accounts: PlaceMarketOrderInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PlaceMarketOrderInstructionAccounts) -> Self {
            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.index_source.clone());

            metas.push(self.accounts.owner.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ReadExchangeRate
    // ....................................................................

    /// Main instruction struct for ReadExchangeRate
    pub struct ReadExchangeRateInstruction {
        pub accounts: ReadExchangeRateInstructionAccountMetas,
        pub data: ReadExchangeRateInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ReadExchangeRate instruction
    #[derive(Debug, Clone, Default)]
    pub struct ReadExchangeRateInstructionAccountMetas {
        pub stake_pool: AccountMeta,
    }

    /// Account pubkeys for ReadExchangeRate instruction
    #[derive(Debug, Clone)]
    pub struct ReadExchangeRateInstructionAccounts {
        pub stake_pool: Pubkey,
    }

    impl ReadExchangeRateInstructionAccounts {
        pub fn new(stake_pool: Pubkey) -> Self {
            Self { stake_pool }
        }
    }

    /// Instruction data for ReadExchangeRate
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ReadExchangeRateInstructionData {}

    impl ReadExchangeRateInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ReadExchangeRateInstruction
    impl ReadExchangeRateInstruction {
        fn discriminator() -> [u8; 8] {
            [76u8, 106u8, 201u8, 30u8, 188u8, 207u8, 136u8, 137u8]
        }

        pub fn data(data: ReadExchangeRateInstructionData) -> Self {
            Self {
                accounts: ReadExchangeRateInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ReadExchangeRateInstructionAccounts) -> Self {
            self.accounts.stake_pool = AccountMeta::new_readonly(accounts.stake_pool, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.stake_pool.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ResetPosition
    // ....................................................................

    /// Main instruction struct for ResetPosition
    pub struct ResetPositionInstruction {
        pub accounts: ResetPositionInstructionAccountMetas,
        pub data: ResetPositionInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ResetPosition instruction
    #[derive(Debug, Clone, Default)]
    pub struct ResetPositionInstructionAccountMetas {
        pub market: AccountMeta,

        pub position: AccountMeta,

        pub user: AccountMeta,
    }

    /// Account pubkeys for ResetPosition instruction
    #[derive(Debug, Clone)]
    pub struct ResetPositionInstructionAccounts {
        pub market: Pubkey,

        pub position: Pubkey,

        pub user: Pubkey,
    }

    impl ResetPositionInstructionAccounts {
        pub fn new(market: Pubkey, position: Pubkey, user: Pubkey) -> Self {
            Self {
                market,

                position,

                user,
            }
        }
    }

    /// Instruction data for ResetPosition
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ResetPositionInstructionData {
        pub side: u8,
    }

    impl ResetPositionInstructionData {
        pub fn new(side: u8) -> Self {
            Self { side }
        }
    }

    /// Implementation for ResetPositionInstruction
    impl ResetPositionInstruction {
        fn discriminator() -> [u8; 8] {
            [26u8, 231u8, 79u8, 28u8, 18u8, 115u8, 223u8, 107u8]
        }

        pub fn data(data: ResetPositionInstructionData) -> Self {
            Self {
                accounts: ResetPositionInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ResetPositionInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user = AccountMeta::new_readonly(accounts.user, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetPublisher
    // ....................................................................

    /// Main instruction struct for SetPublisher
    pub struct SetPublisherInstruction {
        pub accounts: SetPublisherInstructionAccountMetas,
        pub data: SetPublisherInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetPublisher instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetPublisherInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for SetPublisher instruction
    #[derive(Debug, Clone)]
    pub struct SetPublisherInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl SetPublisherInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for SetPublisher
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetPublisherInstructionData {
        pub new_publisher: Pubkey,
    }

    impl SetPublisherInstructionData {
        pub fn new(new_publisher: Pubkey) -> Self {
            Self { new_publisher }
        }
    }

    /// Implementation for SetPublisherInstruction
    impl SetPublisherInstruction {
        fn discriminator() -> [u8; 8] {
            [110u8, 54u8, 4u8, 216u8, 151u8, 85u8, 46u8, 91u8]
        }

        pub fn data(data: SetPublisherInstructionData) -> Self {
            Self {
                accounts: SetPublisherInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetPublisherInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetStaleWindow
    // ....................................................................

    /// Main instruction struct for SetStaleWindow
    pub struct SetStaleWindowInstruction {
        pub accounts: SetStaleWindowInstructionAccountMetas,
        pub data: SetStaleWindowInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetStaleWindow instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetStaleWindowInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub authority: AccountMeta,
    }

    /// Account pubkeys for SetStaleWindow instruction
    #[derive(Debug, Clone)]
    pub struct SetStaleWindowInstructionAccounts {
        pub oracle: Pubkey,

        pub authority: Pubkey,
    }

    impl SetStaleWindowInstructionAccounts {
        pub fn new(oracle: Pubkey, authority: Pubkey) -> Self {
            Self { oracle, authority }
        }
    }

    /// Instruction data for SetStaleWindow
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetStaleWindowInstructionData {
        pub new_stale_after_slots: u64,
    }

    impl SetStaleWindowInstructionData {
        pub fn new(new_stale_after_slots: u64) -> Self {
            Self {
                new_stale_after_slots,
            }
        }
    }

    /// Implementation for SetStaleWindowInstruction
    impl SetStaleWindowInstruction {
        fn discriminator() -> [u8; 8] {
            [189u8, 158u8, 76u8, 38u8, 2u8, 227u8, 121u8, 34u8]
        }

        pub fn data(data: SetStaleWindowInstructionData) -> Self {
            Self {
                accounts: SetStaleWindowInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetStaleWindowInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SettleClose
    // ....................................................................

    /// Main instruction struct for SettleClose
    pub struct SettleCloseInstruction {
        pub accounts: SettleCloseInstructionAccountMetas,
        pub data: SettleCloseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleClose instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleCloseInstructionAccountMetas {
        pub market: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,

        pub index_source: AccountMeta,
    }

    /// Account pubkeys for SettleClose instruction
    #[derive(Debug, Clone)]
    pub struct SettleCloseInstructionAccounts {
        pub market: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,

        pub index_source: Pubkey,
    }

    impl SettleCloseInstructionAccounts {
        pub fn new(
            market: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,

            index_source: Pubkey,
        ) -> Self {
            Self {
                market,

                position,

                user_collateral,

                index_source,
            }
        }
    }

    /// Instruction data for SettleClose
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleCloseInstructionData {}

    impl SettleCloseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SettleCloseInstruction
    impl SettleCloseInstruction {
        fn discriminator() -> [u8; 8] {
            [151u8, 229u8, 199u8, 24u8, 177u8, 153u8, 171u8, 49u8]
        }

        pub fn data(data: SettleCloseInstructionData) -> Self {
            Self {
                accounts: SettleCloseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleCloseInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.index_source.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SettleFill
    // ....................................................................

    /// Main instruction struct for SettleFill
    pub struct SettleFillInstruction {
        pub accounts: SettleFillInstructionAccountMetas,
        pub data: SettleFillInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleFill instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleFillInstructionAccountMetas {
        pub market: AccountMeta,

        pub order_book: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for SettleFill instruction
    #[derive(Debug, Clone)]
    pub struct SettleFillInstructionAccounts {
        pub market: Pubkey,

        pub order_book: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,

        pub payer: Pubkey,
    }

    impl SettleFillInstructionAccounts {
        pub fn new(
            market: Pubkey,

            order_book: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                market,

                order_book,

                position,

                user_collateral,

                payer,
            }
        }
    }

    /// Instruction data for SettleFill
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleFillInstructionData {
        pub seq: u64,
    }

    impl SettleFillInstructionData {
        pub fn new(seq: u64) -> Self {
            Self { seq }
        }
    }

    /// Implementation for SettleFillInstruction
    impl SettleFillInstruction {
        fn discriminator() -> [u8; 8] {
            [197u8, 81u8, 135u8, 50u8, 191u8, 3u8, 171u8, 75u8]
        }

        pub fn data(data: SettleFillInstructionData) -> Self {
            Self {
                accounts: SettleFillInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleFillInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.order_book = AccountMeta::new(accounts.order_book, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SettleFunding
    // ....................................................................

    /// Main instruction struct for SettleFunding
    pub struct SettleFundingInstruction {
        pub accounts: SettleFundingInstructionAccountMetas,
        pub data: SettleFundingInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SettleFunding instruction
    #[derive(Debug, Clone, Default)]
    pub struct SettleFundingInstructionAccountMetas {
        pub market: AccountMeta,

        pub position: AccountMeta,

        pub user_collateral: AccountMeta,

        pub order_book: AccountMeta,

        pub index_source: AccountMeta,
    }

    /// Account pubkeys for SettleFunding instruction
    #[derive(Debug, Clone)]
    pub struct SettleFundingInstructionAccounts {
        pub market: Pubkey,

        pub position: Pubkey,

        pub user_collateral: Pubkey,

        pub order_book: Pubkey,

        pub index_source: Pubkey,
    }

    impl SettleFundingInstructionAccounts {
        pub fn new(
            market: Pubkey,

            position: Pubkey,

            user_collateral: Pubkey,

            order_book: Pubkey,

            index_source: Pubkey,
        ) -> Self {
            Self {
                market,

                position,

                user_collateral,

                order_book,

                index_source,
            }
        }
    }

    /// Instruction data for SettleFunding
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SettleFundingInstructionData {}

    impl SettleFundingInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SettleFundingInstruction
    impl SettleFundingInstruction {
        fn discriminator() -> [u8; 8] {
            [11u8, 251u8, 12u8, 161u8, 199u8, 228u8, 133u8, 87u8]
        }

        pub fn data(data: SettleFundingInstructionData) -> Self {
            Self {
                accounts: SettleFundingInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SettleFundingInstructionAccounts) -> Self {
            self.accounts.market = AccountMeta::new(accounts.market, false);

            self.accounts.position = AccountMeta::new(accounts.position, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.order_book = AccountMeta::new_readonly(accounts.order_book, false);

            self.accounts.index_source = AccountMeta::new_readonly(accounts.index_source, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.position.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.order_book.clone());

            metas.push(self.accounts.index_source.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateApy
    // ....................................................................

    /// Main instruction struct for UpdateApy
    pub struct UpdateApyInstruction {
        pub accounts: UpdateApyInstructionAccountMetas,
        pub data: UpdateApyInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateApy instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateApyInstructionAccountMetas {
        pub oracle: AccountMeta,

        pub instruction_sysvar: AccountMeta,
    }

    /// Account pubkeys for UpdateApy instruction
    #[derive(Debug, Clone)]
    pub struct UpdateApyInstructionAccounts {
        pub oracle: Pubkey,

        pub instruction_sysvar: Pubkey,
    }

    impl UpdateApyInstructionAccounts {
        pub fn new(oracle: Pubkey, instruction_sysvar: Pubkey) -> Self {
            Self {
                oracle,

                instruction_sysvar,
            }
        }
    }

    /// Instruction data for UpdateApy
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateApyInstructionData {
        pub apy: u64,

        pub version: u64,
    }

    impl UpdateApyInstructionData {
        pub fn new(apy: u64, version: u64) -> Self {
            Self { apy, version }
        }
    }

    /// Implementation for UpdateApyInstruction
    impl UpdateApyInstruction {
        fn discriminator() -> [u8; 8] {
            [94u8, 110u8, 147u8, 45u8, 73u8, 167u8, 222u8, 77u8]
        }

        pub fn data(data: UpdateApyInstructionData) -> Self {
            Self {
                accounts: UpdateApyInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateApyInstructionAccounts) -> Self {
            self.accounts.oracle = AccountMeta::new(accounts.oracle, false);

            self.accounts.instruction_sysvar =
                AccountMeta::new_readonly(accounts.instruction_sysvar, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.oracle.clone());

            metas.push(self.accounts.instruction_sysvar.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawCollateral
    // ....................................................................

    /// Main instruction struct for WithdrawCollateral
    pub struct WithdrawCollateralInstruction {
        pub accounts: WithdrawCollateralInstructionAccountMetas,
        pub data: WithdrawCollateralInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawCollateral instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawCollateralInstructionAccountMetas {
        pub user: AccountMeta,

        pub market: AccountMeta,

        pub user_collateral: AccountMeta,

        pub vault: AccountMeta,

        pub user_ata: AccountMeta,

        pub collateral_mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawCollateral instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawCollateralInstructionAccounts {
        pub user: Pubkey,

        pub market: Pubkey,

        pub user_collateral: Pubkey,

        pub vault: Pubkey,

        pub user_ata: Pubkey,

        pub collateral_mint: Pubkey,
    }

    impl WithdrawCollateralInstructionAccounts {
        pub fn new(
            user: Pubkey,

            market: Pubkey,

            user_collateral: Pubkey,

            vault: Pubkey,

            user_ata: Pubkey,

            collateral_mint: Pubkey,
        ) -> Self {
            Self {
                user,

                market,

                user_collateral,

                vault,

                user_ata,

                collateral_mint,
            }
        }
    }

    /// Instruction data for WithdrawCollateral
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawCollateralInstructionData {
        pub amount: u64,
    }

    impl WithdrawCollateralInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for WithdrawCollateralInstruction
    impl WithdrawCollateralInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 135u8, 168u8, 106u8, 139u8, 214u8, 138u8, 150u8]
        }

        pub fn data(data: WithdrawCollateralInstructionData) -> Self {
            Self {
                accounts: WithdrawCollateralInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawCollateralInstructionAccounts) -> Self {
            self.accounts.user = AccountMeta::new_readonly(accounts.user, true);

            self.accounts.market = AccountMeta::new_readonly(accounts.market, false);

            self.accounts.user_collateral = AccountMeta::new(accounts.user_collateral, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.user_ata = AccountMeta::new(accounts.user_ata, false);

            self.accounts.collateral_mint =
                AccountMeta::new_readonly(accounts.collateral_mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.market.clone());

            metas.push(self.accounts.user_collateral.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.user_ata.clone());

            metas.push(self.accounts.collateral_mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Observation
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Observation {
    pub slot: u64,

    pub mid: u64,

    pub cumulative_mid: [u8; 16],
}

impl Observation {
    pub fn new(slot: u64, mid: u64, cumulative_mid: [u8; 16]) -> Self {
        Self {
            slot,

            mid,

            cumulative_mid,
        }
    }
}

/// Custom struct: Order
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Order {
    pub owner: Pubkey,

    pub price: u64,

    pub size: u64,

    pub seq: u64,

    pub active: u8,

    pub _pad: [u8; 7],
}

impl Order {
    pub fn new(owner: Pubkey, price: u64, size: u64, seq: u64, active: u8, _pad: [u8; 7]) -> Self {
        Self {
            owner,

            price,

            size,

            seq,

            active,

            _pad,
        }
    }
}

/// Custom struct: OrderBook
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OrderBook {
    pub next_seq: u64,

    pub best_bid: u64,

    pub best_ask: u64,

    pub event_read_cursor: u64,

    pub event_write_cursor: u64,

    pub twap_cursor: u64,

    pub market: Pubkey,

    pub bump: u8,

    pub _pad: [u8; 7],

    pub bids: [Order; 64],

    pub asks: [Order; 64],

    pub events: [OutEvent; 128],

    pub observations: [Observation; 16],
}

impl OrderBook {
    pub fn new(
        next_seq: u64,

        best_bid: u64,

        best_ask: u64,

        event_read_cursor: u64,

        event_write_cursor: u64,

        twap_cursor: u64,

        market: Pubkey,

        bump: u8,

        _pad: [u8; 7],

        bids: [Order; 64],

        asks: [Order; 64],

        events: [OutEvent; 128],

        observations: [Observation; 16],
    ) -> Self {
        Self {
            next_seq,

            best_bid,

            best_ask,

            event_read_cursor,

            event_write_cursor,

            twap_cursor,

            market,

            bump,

            _pad,

            bids,

            asks,

            events,

            observations,
        }
    }
}

/// Custom struct: OutEvent
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OutEvent {
    pub seq: u64,

    pub price: u64,

    pub size: u64,

    pub owner: Pubkey,

    pub counterparty: Pubkey,

    pub entry_total_lamports: u64,

    pub entry_pool_token_supply: u64,

    pub settled: u8,

    pub kind: u8,

    pub side: u8,

    pub _pad: [u8; 5],
}

impl OutEvent {
    pub fn new(
        seq: u64,

        price: u64,

        size: u64,

        owner: Pubkey,

        counterparty: Pubkey,

        entry_total_lamports: u64,

        entry_pool_token_supply: u64,

        settled: u8,

        kind: u8,

        side: u8,

        _pad: [u8; 5],
    ) -> Self {
        Self {
            seq,

            price,

            size,

            owner,

            counterparty,

            entry_total_lamports,

            entry_pool_token_supply,

            settled,

            kind,

            side,

            _pad,
        }
    }
}

/// Custom struct: PerpMarket
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PerpMarket {
    pub index_source: Pubkey,

    pub collateral_mint: Pubkey,

    pub funding_k: u64,

    pub max_funding: u64,

    pub funding_epoch_slots: u64,

    pub initial_margin_bps: u16,

    pub maintenance_margin_bps: u16,

    pub authority: Pubkey,

    pub vault: Pubkey,

    pub funding_epoch: u64,

    pub index_n: u64,

    pub index_d: u64,

    pub funding_accumulator: i128,

    pub bump: u8,
}

impl PerpMarket {
    pub fn new(
        index_source: Pubkey,

        collateral_mint: Pubkey,

        funding_k: u64,

        max_funding: u64,

        funding_epoch_slots: u64,

        initial_margin_bps: u16,

        maintenance_margin_bps: u16,

        authority: Pubkey,

        vault: Pubkey,

        funding_epoch: u64,

        index_n: u64,

        index_d: u64,

        funding_accumulator: i128,

        bump: u8,
    ) -> Self {
        Self {
            index_source,

            collateral_mint,

            funding_k,

            max_funding,

            funding_epoch_slots,

            initial_margin_bps,

            maintenance_margin_bps,

            authority,

            vault,

            funding_epoch,

            index_n,

            index_d,

            funding_accumulator,

            bump,
        }
    }
}

/// Custom struct: Position
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Position {
    pub market: Pubkey,

    pub owner: Pubkey,

    pub side: u8,

    pub notional: u64,

    pub entry_n_sum: u128,

    pub entry_d_sum: u128,

    pub collateral: u64,

    pub last_funding_epoch: u64,

    pub closed_notional: u64,

    pub open_slot: u64,

    pub bump: u8,
}

impl Position {
    pub fn new(
        market: Pubkey,

        owner: Pubkey,

        side: u8,

        notional: u64,

        entry_n_sum: u128,

        entry_d_sum: u128,

        collateral: u64,

        last_funding_epoch: u64,

        closed_notional: u64,

        open_slot: u64,

        bump: u8,
    ) -> Self {
        Self {
            market,

            owner,

            side,

            notional,

            entry_n_sum,

            entry_d_sum,

            collateral,

            last_funding_epoch,

            closed_notional,

            open_slot,

            bump,
        }
    }
}

/// Custom struct: UserCollateral
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UserCollateral {
    pub deposited: u64,

    pub reserved: u64,

    pub bump: u8,
}

impl UserCollateral {
    pub fn new(deposited: u64, reserved: u64, bump: u8) -> Self {
        Self {
            deposited,

            reserved,

            bump,
        }
    }
}

/// Custom struct: YieldOracle
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct YieldOracle {
    pub apy: u64,

    pub version: u64,

    pub last_update_slot: u64,

    pub publisher: Pubkey,

    pub authority: Pubkey,

    pub stale_after_slots: u64,

    pub bump: u8,
}

impl YieldOracle {
    pub fn new(
        apy: u64,

        version: u64,

        last_update_slot: u64,

        publisher: Pubkey,

        authority: Pubkey,

        stale_after_slots: u64,

        bump: u8,
    ) -> Self {
        Self {
            apy,

            version,

            last_update_slot,

            publisher,

            authority,

            stale_after_slots,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
