[package]
name = "fructus"
version = "0.1.0"
description = "Fructus — a Solana protocol for trading yield futures."
edition = "2021"
license = "MIT"
repository = "https://github.com/LaiTszKin/fructus"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
solana-program = { workspace = true }
